---
- name: blockinfile module demo
  hosts: all
  become: false
  tasks:

- name: Generate /etc/hosts file
  ansible.builtin.blockinfile:
    state: present
    dest: /etc/hosts
    content: |
      10.0.0.1 demo demo.example.com
