---
- name: user module demo
  hosts: all
  become: true
  vars:
    myuser: "example"
    groups:
      - adm
      - sys
  tasks:
    - name: adding secondary groups
      user:
        name: "{{ myuser }}"
        groups: "{{ groups }}"
        append: true
